#!/usr/bin/env Rscript

# This script performs PARC clustering of WES-derived gene-level features.
# It loads UMAP coordinates and the long-format feature table generated by
# 1_features_loading.R, runs PARC clustering through the Python backend,
# and saves cluster assignments and UMAP plots.
# Usage:
# R_LIBS= R_LIBS_USER= R_LIBS_SITE= R_PROFILE_USER=/dev/null \
# Rscript --vanilla "Gene-level imputation/2_clustering.R" config/local_config.yaml

conda_lib <- file.path(Sys.getenv("CONDA_PREFIX"), "lib/R/library")
if (nzchar(Sys.getenv("CONDA_PREFIX")) && dir.exists(conda_lib)) {
	.libPaths(conda_lib)
}

suppressPackageStartupMessages({
	library(data.table)
	library(ggplot2)
	library(colorspace)
	library(reticulate)
})

# Clustering parameters can be adjusted.
parc_params <- list(
	knn = 30,
	resolution = 1
)

get_script_path <- function() {
	args <- commandArgs(trailingOnly = FALSE)
	file_arg <- grep("^--file=", args, value = TRUE)

	if (length(file_arg) == 0) {
		stop("Cannot determine script path.")
	}

	normalizePath(sub("^--file=", "", file_arg[1]))
}

script_path <- get_script_path()
script_dir <- dirname(script_path)
repo_dir <- normalizePath(file.path(script_dir, ".."))

args <- commandArgs(trailingOnly = TRUE)
config <- if (length(args) >= 1) args[1] else "config/local_config.yaml"

if (!grepl("^/", config)) {
	config <- file.path(repo_dir, config)
}

read_config <- function(key) {
	system2(
		"python",
		args = c(file.path(repo_dir, "scripts/read_config.py"), config, key),
		stdout = TRUE
	)
}

resolve_path <- function(path) {
	if (grepl("^/", path)) {
		return(path)
	}

	file.path(repo_dir, path)
}

results_dir <- resolve_path(read_config("directories.results_dir"))
output_dir <- file.path(results_dir, "Results")
figures_dir <- file.path(output_dir, "Figures")

umap_file <- file.path(output_dir, "raw_umap_result.tsv")
long_tsv <- file.path(output_dir, "raw_ft_long.tsv")
parc_script <- file.path(script_dir, "functions", "run_parc.py")

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figures_dir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(umap_file)) {
	stop("UMAP file not found: ", umap_file)
}

if (!file.exists(long_tsv)) {
	stop("Long-format feature table not found: ", long_tsv)
}

if (!file.exists(parc_script)) {
	stop("PARC Python script not found: ", parc_script)
}

umap_result <- fread(umap_file)

if (!"Sample" %in% colnames(umap_result)) {
	stop("Column 'Sample' not found in UMAP file.")
}

source_python(parc_script)

run_parc <- function(long_tsv, knn, resolution, umap_dt) {
	cat("Running PARC with k=", knn, ", resolution=", resolution, "\n", sep = "")

	samples_labels <- parc_labels_from_long_tsv(
		long_tsv,
		knn = as.integer(knn),
		res = resolution
	)

	labels <- data.table(
		Sample = as.character(unlist(samples_labels[[1]])),
		PARC = as.integer(unlist(samples_labels[[2]]))
	)

	umap_parc <- copy(umap_dt)
	umap_parc[, Cluster := labels$PARC[match(Sample, labels$Sample)]]

	if (all(is.na(umap_parc$Cluster))) {
		stop("No PARC labels matched UMAP sample names.")
	}

	umap_parc[, Cluster := as.factor(Cluster)]

	plot_title <- paste0("k=", knn, " resolution=", resolution)

	p <- ggplot(umap_parc, aes(x = UMAP1, y = UMAP2, color = Cluster)) +
		geom_point(size = 1) +
		theme_test() +
		labs(
			title = plot_title,
			x = "UMAP 1",
			y = "UMAP 2"
		) +
		scale_color_discrete_qualitative(palette = "Dark3")

	list(plot = p, data = umap_parc)
}

parc <- run_parc(
	long_tsv = long_tsv,
	knn = parc_params$knn,
	resolution = parc_params$resolution,
	umap_dt = umap_result
)

output_tag <- paste0("k", parc_params$knn, "r", parc_params$resolution)

fwrite(
	parc$data,
	file.path(output_dir, paste0("umap_parc_", output_tag, ".tsv")),
	sep = "\t"
)

sample_map <- copy(parc$data)
sample_map[, c("UMAP1", "UMAP2") := NULL]

fwrite(
	sample_map,
	file.path(output_dir, "sample_kit_cluster_map.tsv"),
	sep = "\t"
)

pdf(file.path(figures_dir, "PARC_clustering.pdf"), width = 6, height = 5.5)
print(parc$plot)
dev.off()

cat("PARC clustering completed.\n")
